name: deploy-test-aws-bucket.yml
on:
  pull_request:
    types: [labeled]
    branch:
      - 'develop*'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      should_run_jobs: ${{ github.event.label.name == 'cd to aws test'}} # && github.event.pull_request.merged == true }}
    steps:
      - name: Check if jobs should run
        run: echo "Evaluated conditions ..."

  build-and-deploy:
    needs: setup
    if: needs.setup.outputs.should_run_jobs == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build Vue.js application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET }} --delete --acl public-read

#      - name: Invalidate CloudFront cache (optional)
#        if: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
#        run: |
#          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
